# Generated by Django 4.1.6 on 2023-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
