# Generated by Django 4.1.6 on 2023-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_category_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_account',
            field=models.BooleanField(default=True),
        ),
    ]
