# Generated by Django 4.1.6 on 2023-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0008_delete_categoryclass_category_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='account_type',
            field=models.CharField(choices=[('Asset/Expense', 'asset_expense'), ('Liabilities/Income/Capital', 'liabilities_equity')], default='increase_debit', max_length=40),
        ),
    ]
