# Generated by Django 4.1.6 on 2023-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0011_alter_category_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credit',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=120),
        ),
    ]
