# Generated by Django 4.1.6 on 2023-05-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_transaction_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpensesList',
        ),
    ]
